name: Lint
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  clippy:
    name: Cargo clippy & fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable
    - name: cargo fmt
      run: cargo fmt --all -- --check
    - name: cargo clippy
      run: cargo clippy --all-features --tests -- -D warnings
